### ISSUE TITLE
Upgrade To DotNet Core 3.0

### ISSUE THREAD

**Issue by charles-kuperus** [Lupusa87/BlazorSvgHelper#2]
Good day @Lupusa87, 

With the release of dotnet core 3.0 I found this repo and thought to add an upgrade for this project. I have the changes locally but cannot push the new branch. 

Let me know if you interested in this code changes? 

Regards 
Charles Kuperus

**Comment by Lupusa87** [comment]
Hello, thank you.

Sure I will be happy if you contribute update to this project.

I will check it at weekends and do what will be required from my side.

**Comment by charles-kuperus** [comment]
Good day @Lupusa87, 

I have tried to push the changes to a new branch but it gives me the below error. 

git push -u origin UpgradeToDotNetCore3.0
remote: Permission to Lupusa87/BlazorSvgHelper.git denied to charles-kuperus.
fatal: unable to access 'https://github.com/Lupusa87/BlazorSvgHelper.git/': The requested URL returned error: 403

**GIT LOGS**
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.21.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: c:\Source\GitHub\Lupusa87\BlazorSvgHelper
> git fetch
> git status -z -u
> git config --global user.email
> git symbolic-ref --short HEAD
> git config --global user.name
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show -s --format=%an <%ae> [%ai] d9c13a2596bed260a5f6a69f0b7d02724008eae4
> git show -s --format=%H
%ae
%P
%B d9c13a2596bed260a5f6a69f0b7d02724008eae4
> git show -s --format=%an <%ae> [%ai] 8e6e995b7ac4b19265b390aec4ce8607a2d79323
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git push
fatal: The current branch UpgradeToDotNetCore3.0 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin UpgradeToDotNetCore3.0
> git push -u origin UpgradeToDotNetCore3.0
remote: Permission to Lupusa87/BlazorSvgHelper.git denied to charles-kuperus.
fatal: unable to access 'https://github.com/Lupusa87/BlazorSvgHelper.git/': The requested URL returned error: 403
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse UpgradeToDotNetCore3.0
> git rev-parse --symbolic-full-name UpgradeToDotNetCore3.0@{u}
fatal: no upstream configured for branch 'UpgradeToDotNetCore3.0'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

**Comment by charles-kuperus** [comment]
Good day @Lupusa87 

Seems like I cannot push to your repository. 

So here is the code changes I made then you may review and commit these yourself then may we might receive an updated nuget package. 

[BlazorSvgHelper.zip](https://github.com/Lupusa87/BlazorSvgHelper/files/3678347/BlazorSvgHelper.zip)

Regards 
Charles Kuperus

**Comment by Lupusa87** [comment]
@charles-kuperus Hi, I am sorry I was not getting notifications and also vas very busy.
I am going to update project to RC and update nuget package too.
Please check later and if there will be missing anything let me know or make PR request.

**Comment by Lupusa87** [comment]
Please check latest changes and if you are missing anything please make PR.
Now I have time and can react fast to any needs.
