### ISSUE TITLE
Forked and used charles-kuperus update

### ISSUE THREAD

**Issue by Flearz** [Lupusa87/BlazorSvgHelper#4]
I forked your project, it's now updated and got some features.
Could you let me push ? or do it yourself ? Your work is really useful.
Rihen

**Comment by Lupusa87** [comment]
Thank you.
I do not see any PR.
I am updating it now, check later and if you want to add features please create PR request.

**Comment by Lupusa87** [comment]
I have applied those changes, thank you so much and sorry for my late action.
